# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  sarnia.ca:
    site_hosts:
      - canonical: dev.sarnia.cos.city.sarnia.on.ca
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: zachary.collette@sarnia.ca
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
