# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  sarnia.ca:
    site_hosts:
      - canonical: ip-10-30-14-118.ca-central-1.compute.internal
      - canonical: ip-10-30-14-242.ca-central-1.compute.internal
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@cos-gitlab-prod.cos.city.sarnia.on.ca:sarnia-website/sarnia.ca.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: develop
    db_create: false
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: true
    env:
      wp_home: https://staging.sarnia.ca
      wp_siteurl: https://staging.sarnia.ca/wp
      db_name: sarnia_ca_staging
      db_user: sarnia_ca_staging
      db_host: a301us18-sql003.cq21knrlnmdp.ca-central-1.rds.amazonaws.com
      mysql_client_flags: "MYSQLI_CLIENT_SSL"

